version: '3.7'
services:

  db:
    image: postgres:15.2
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: librarydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
